agent.sources = tailSource
agent.channels = fileChannel
agent.sinks = kafkaSink

agent.sources.tailSource.type = TAILDIR
agent.sources.tailSource.filegroups = f1
agent.sources.tailSource.filegroups.f1 = /var/log/honeypot-preprocessed/events.jsonl
agent.sources.tailSource.positionFile = /var/lib/flume/honeypot-edge-taildir-position.json
agent.sources.tailSource.skipToEnd = true
agent.sources.tailSource.fileHeader = true
agent.sources.tailSource.fileHeaderKey = file
agent.sources.tailSource.channels = fileChannel

agent.channels.fileChannel.type = file
agent.channels.fileChannel.checkpointDir = /var/lib/flume/checkpoint
agent.channels.fileChannel.dataDirs = /var/lib/flume/data
agent.channels.fileChannel.capacity = 100000
agent.channels.fileChannel.transactionCapacity = 1000

agent.sinks.kafkaSink.type = org.apache.flume.sink.kafka.KafkaSink
agent.sinks.kafkaSink.kafka.bootstrap.servers = 203.0.113.20:9092
agent.sinks.kafkaSink.kafka.topic = honeypot3_clean
agent.sinks.kafkaSink.kafka.flumeBatchSize = 100
agent.sinks.kafkaSink.kafka.producer.acks = 1
agent.sinks.kafkaSink.channel = fileChannel
